name: AI Trading Bot Scanner

on:
  schedule:
    # این زمان به وقت جهانی (UTC) است.
    # 0 1,7,13,19 * * * یعنی ساعت 1,7,13,19 به وقت UTC
    # که به وقت ایران میشه: 4:30 صبح، 10:30 صبح، 4:30 عصر، 10:30 شب
    - cron: '0 1,7,13,19 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install yfinance pandas_ta xgboost requests vaderSentiment

      - name: Run AI Bot
        run: |
          python robot.py
